### ISSUE TITLE
List with euca instances

### ISSUE THREAD

**Issue by jeffjapan** [jacobian/openstack.compute#2]
## If you create an instance with euca tools:

euca-run-instances ami-71311d1d -k mykey -t m1.tiny
## Then access it with the openstack api:

openstack-compute --username <MYUSER> --apikey <MYKEY> --auth-url http://192.168.200.50:8774/v1.0/ list
## openstack.compute blows up because the public ip is empty:

Traceback (most recent call last):
  File "/home/jwilcox/code/openstackDashboard/1multi/openstack-dashboard/.dashboard-venv/bin/openstack-compute", line 8, in <module>
    load_entry_point('openstack.compute==2.0a1', 'console_scripts', 'openstack-compute')()
  File "/home/jwilcox/code/openstackDashboard/1multi/openstack-dashboard/.dashboard-venv/lib/python2.6/site-packages/openstack.compute-2.0a1-py2.6.egg/openstack/compute/shell.py", line 485, in main
    ComputeShell().main(sys.argv[1:])
  File "/home/jwilcox/code/openstackDashboard/1multi/openstack-dashboard/.dashboard-venv/lib/python2.6/site-packages/openstack.compute-2.0a1-py2.6.egg/openstack/compute/shell.py", line 142, in main
    args.func(args)
  File "/home/jwilcox/code/openstackDashboard/1multi/openstack-dashboard/.dashboard-venv/lib/python2.6/site-packages/openstack.compute-2.0a1-py2.6.egg/openstack/compute/shell.py", line 347, in do_list
    print_list(self.compute.servers.list(), ['ID', 'Name', 'Status', 'Public IP', 'Private IP'])
  File "/home/jwilcox/code/openstackDashboard/1multi/openstack-dashboard/.dashboard-venv/lib/python2.6/site-packages/openstack.compute-2.0a1-py2.6.egg/openstack/compute/shell.py", line 472, in print_list
    row.append(getattr(o, field.lower().replace(' ', '_'), ''))
  File "/home/jwilcox/code/openstackDashboard/1multi/openstack-dashboard/.dashboard-venv/lib/python2.6/site-packages/openstack.compute-2.0a1-py2.6.egg/openstack/compute/servers.py", line 98, in public_ip
    return self.addresses['public'][0]
IndexError: list index out of range

**Comment by jeffjapan** [comment]
I  generated a git patch, but I couldn't find a way to attach the patch to this issue, so I pushed the (4 line) patch to:
https://github.com/jeffjapan/openstack.compute
